# Generated by Django 3.0.5 on 2020-05-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariFieldObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariFieldSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the field', max_length=30, verbose_name='name')),
                ('choices', models.CharField(blank=True, help_text='Optionally, a comma-separated list of choices', max_length=30, verbose_name='choices')),
                ('on_list', models.BooleanField(default=False, help_text="If this should appear on a list -- Note: This field's operation depends on the programming of the app that uses it.  It has no effect unless used by the app", verbose_name='on list')),
                ('on_filter', models.BooleanField(default=False, help_text="If this should appear as an option for filtering -- Note: This field's operation depends on the programming of the app that uses it.  It has no effect unless used by the app", verbose_name='on filter')),
                ('spec_help_text', models.CharField(blank=True, help_text='The help text to be displayed', max_length=255, verbose_name='help_text')),
                ('content_type', models.ForeignKey(help_text='The type of object(the model) to which this field will apply.  Note: The choices are limted by Vari Field Spec Choices', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('vari_field_objects', models.ManyToManyField(blank=True, help_text='The objects to which this field will apply', to='varifields.VariFieldObject')),
            ],
            options={
                'verbose_name': 'Variable Field',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VariFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.CharField(blank=True, help_text='The value of the additional info', max_length=255, verbose_name='content')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('spec', models.ForeignKey(help_text='The spec for this additional info', on_delete=django.db.models.deletion.CASCADE, related_name='value', to='varifields.VariFieldSpec', verbose_name='spec')),
            ],
            options={
                'verbose_name': 'Value for a variable field',
                'ordering': ['spec'],
            },
        ),
        migrations.CreateModel(
            name='VariFieldSpecChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(help_text='This is for limiting the choices in the content_type field of variable field specifications.  It is unlikely that you should have to change this often', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
