# Generated by Django 3.0.5 on 2020-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varifields', '0002_auto_20200417_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varifieldspec',
            name='object_ids',
        ),
        migrations.AddField(
            model_name='varifieldspec',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ObjectId',
        ),
    ]
