# Generated by Django 3.0.5 on 2020-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varifields', '0003_auto_20200417_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariFieldObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='varifieldspec',
            name='object_id',
        ),
        migrations.AddField(
            model_name='varifieldspec',
            name='obj',
            field=models.ManyToManyField(blank=True, help_text='The objects to which this field will apply', to='varifields.VariFieldObject'),
        ),
    ]
