# Generated by Django 3.0.5 on 2020-04-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varifields', '0004_auto_20200418_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varifieldspec',
            old_name='obj',
            new_name='vari_field_objects',
        ),
    ]
