# Generated by Django 3.0.5 on 2020-06-23 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trouble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (10, 10)], default=0, help_text='The status of the ticket as of this update', verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Any notes for this item', verbose_name='notes')),
                ('date_updated', models.DateField(default=datetime.date(2020, 6, 23), help_text='The date of this update', verbose_name='date')),
                ('ticket', models.ForeignKey(help_text='The ticket for this response', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='trouble.Ticket')),
                ('updater', models.ForeignKey(blank=True, help_text='The tech who updated this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TicketUpdate',
        ),
    ]
