# Generated by Django 3.0.5 on 2020-06-23 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble', '0002_auto_20200623_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketresponse',
            name='date_updated',
            field=models.DateField(default=datetime.date.today, help_text='The date of this update', verbose_name='date'),
        ),
    ]
