# Generated by Django 3.0.5 on 2020-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (ex. "Desktop", "Tablet" )', max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description of the category (ex. "Desk", "Lendable Items" )', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar_name', models.CharField(help_text="The identifying name for this item (ex Joe's laptop)", max_length=30, verbose_name='familiar name')),
                ('serial_number', models.CharField(blank=True, help_text="The item's serial number", max_length=30, verbose_name='serial number')),
                ('asset_number', models.CharField(blank=True, help_text="The item's asset number", max_length=30, verbose_name='asset number')),
                ('barcode', models.CharField(blank=True, help_text="The item's barcode", max_length=50, verbose_name='barcode')),
                ('hostname', models.CharField(blank=True, help_text="The item's network name or hostname", max_length=50, verbose_name='host name')),
                ('condition', models.IntegerField(blank=True, choices=[(12, 'U Unusable'), (9, 'F Disfunctional'), (6, 'D Degraded'), (3, 'W Worn but fully operational'), (0, 'N New or like new')], help_text='The condition of the item', null=True, verbose_name='condition')),
                ('inventory', models.IntegerField(blank=True, choices=[(0, 'N Not yet in use'), (3, 'I In use'), (6, 'S Stored'), (9, 'P Pending Removal'), (12, 'R Removed from Inventory')], help_text='The inventory status of the item', null=True, verbose_name='inventory status')),
                ('notes', models.TextField(blank=True, help_text='Any notes for this item', verbose_name='notes')),
            ],
            options={
                'ordering': ['makemodel', 'inventory'],
            },
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date this record was created', verbose_name='date')),
                ('description', models.TextField(blank=True, help_text='The description of what happened', verbose_name='description')),
            ],
            options={
                'ordering': ['item', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the building, vehicle, campus, etc.. ', max_length=30, verbose_name='Name')),
                ('abbreviation', models.CharField(help_text='An abbreviation for the location', max_length=30, verbose_name='Abbreviation')),
                ('priority', models.IntegerField(default=5, help_text='A number for sorting (in default order, low numbers are first)', verbose_name='Priority')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='The models brand', max_length=30, verbose_name='Brand')),
                ('name', models.CharField(blank=True, help_text='The model name', max_length=30, verbose_name='Model Name')),
                ('part_number', models.CharField(blank=True, help_text='The part number or designation other than the marketed model name', max_length=30, verbose_name='Part Number')),
                ('description', models.CharField(blank=True, help_text="The description (ex 'Laptop Computer', 'Tablet', 'Printer'", max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Make/Model',
                'verbose_name_plural': 'Makes/Models',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the role (ex. "Staff", "Lendable" )', max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description of the role (ex. "Items Apporoved for the Domain", "Lendable Items" )', max_length=100, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, help_text='The name of the setting', max_length=130, verbose_name='key')),
                ('value', models.TextField(blank=True, help_text='The value of the setting', verbose_name='value')),
            ],
        ),
    ]
