# Generated by Django 3.0.5 on 2020-04-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200417_0040'),
        ('inventory', '0002_auto_20200417_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='The person or organization who is currently using or taken responsible for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_item', to='entities.Entity', verbose_name='borrower'),
        ),
        migrations.AlterField(
            model_name='item',
            name='keeper',
            field=models.ForeignKey(blank=True, help_text='The person or organization who normally uses or is responsible for the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_item', to='entities.Entity', verbose_name='keeper'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lessor',
            field=models.ForeignKey(blank=True, help_text='The owner or organization from which this item is leased or borrowed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posession', to='entities.Entity', verbose_name='lessor'),
        ),
    ]
