# Generated by Django 3.0.5 on 2020-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200508_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquery',
            name='paginate_by',
            field=models.IntegerField(default=10, verbose_name='paginate by'),
        ),
    ]
