# Generated by Django 3.0.5 on 2020-06-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200607_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquery',
            name='roles_operator',
            field=models.CharField(choices=[('itemxroles__roles__in', 'are in')], default='itemxroles__roles__in', max_length=50, verbose_name='roles operator'),
        ),
        migrations.AddField(
            model_name='itemquery',
            name='roles_use',
            field=models.BooleanField(default=False, verbose_name='use roles'),
        ),
        migrations.AddField(
            model_name='itemquery',
            name='roles_value',
            field=models.ManyToManyField(blank=True, help_text='The roles that are assigned to this item', to='inventory.Role', verbose_name='roles'),
        ),
        migrations.CreateModel(
            name='ItemXRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, help_text="This history record's item", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemxrole', to='inventory.Item', verbose_name='item')),
                ('role', models.ForeignKey(blank=True, help_text="This history record's role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemxrole', to='inventory.Role', verbose_name='role')),
            ],
        ),
    ]
