# Generated by Django 3.0.5 on 2020-06-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200608_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makemodel',
            name='categories',
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='roles_operator',
            field=models.CharField(choices=[('itemxrole__role__in', 'are in')], default='itemxrole__role__in', max_length=50, verbose_name='roles operator'),
        ),
        migrations.AlterField(
            model_name='itemxrole',
            name='item',
            field=models.ForeignKey(blank=True, help_text="This role's item", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemxrole', to='inventory.Item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='itemxrole',
            name='role',
            field=models.ForeignKey(blank=True, help_text="This item's role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemxrole', to='inventory.Role', verbose_name='role'),
        ),
        migrations.CreateModel(
            name='MakeModelXCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, help_text="This makemodel's category", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makemodelxcategory', to='inventory.Category', verbose_name='category')),
                ('makemodel', models.ForeignKey(blank=True, help_text="This category's makemodel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makemodelxcategory', to='inventory.MakeModel', verbose_name='makemodel')),
            ],
        ),
    ]
