# Generated by Django 3.0.5 on 2020-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200611_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquery',
            name='orderby1',
            field=models.CharField(choices=[('familiar_name', 'Name'), ('-familiar_name', 'Name DESC'), ('serial_number', 'Serial Number'), ('-serial_number', 'Serial Number DESC'), ('makemodel', 'Model'), ('-makemodel', 'Model DESC'), ('asset_number', 'Asset Number'), ('-asset_number', 'Asset Number DESC'), ('barcode', 'Barcode'), ('-barcode', 'Barcode DESC'), ('hostname', 'Host name'), ('-hostname', 'Host name DESC'), ('roles', 'Roles'), ('-roles', 'Roles DESC'), ('home', 'Home'), ('-home', 'Home DESC'), ('location', 'Current Location'), ('-location', 'Current Location DESC'), ('condition', 'Condition'), ('-condition', 'Condition DESC'), ('inventory', 'Inventory Status'), ('-inventory', 'Inventory Status DESC'), ('keeper', 'Keeper'), ('-keeper', 'Keeper DESC'), ('borrower', 'Borrower'), ('-borrower', 'Borrower DESC'), ('lessor', 'Lessor'), ('-lessor', 'Lessor DESC')], default='makemodel', max_length=20, verbose_name='order by'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='orderby2',
            field=models.CharField(choices=[('familiar_name', 'Name'), ('-familiar_name', 'Name DESC'), ('serial_number', 'Serial Number'), ('-serial_number', 'Serial Number DESC'), ('makemodel', 'Model'), ('-makemodel', 'Model DESC'), ('asset_number', 'Asset Number'), ('-asset_number', 'Asset Number DESC'), ('barcode', 'Barcode'), ('-barcode', 'Barcode DESC'), ('hostname', 'Host name'), ('-hostname', 'Host name DESC'), ('roles', 'Roles'), ('-roles', 'Roles DESC'), ('home', 'Home'), ('-home', 'Home DESC'), ('location', 'Current Location'), ('-location', 'Current Location DESC'), ('condition', 'Condition'), ('-condition', 'Condition DESC'), ('inventory', 'Inventory Status'), ('-inventory', 'Inventory Status DESC'), ('keeper', 'Keeper'), ('-keeper', 'Keeper DESC'), ('borrower', 'Borrower'), ('-borrower', 'Borrower DESC'), ('lessor', 'Lessor'), ('-lessor', 'Lessor DESC')], default='inventory', max_length=20, verbose_name='order by'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='orderby3',
            field=models.CharField(choices=[('familiar_name', 'Name'), ('-familiar_name', 'Name DESC'), ('serial_number', 'Serial Number'), ('-serial_number', 'Serial Number DESC'), ('makemodel', 'Model'), ('-makemodel', 'Model DESC'), ('asset_number', 'Asset Number'), ('-asset_number', 'Asset Number DESC'), ('barcode', 'Barcode'), ('-barcode', 'Barcode DESC'), ('hostname', 'Host name'), ('-hostname', 'Host name DESC'), ('roles', 'Roles'), ('-roles', 'Roles DESC'), ('home', 'Home'), ('-home', 'Home DESC'), ('location', 'Current Location'), ('-location', 'Current Location DESC'), ('condition', 'Condition'), ('-condition', 'Condition DESC'), ('inventory', 'Inventory Status'), ('-inventory', 'Inventory Status DESC'), ('keeper', 'Keeper'), ('-keeper', 'Keeper DESC'), ('borrower', 'Borrower'), ('-borrower', 'Borrower DESC'), ('lessor', 'Lessor'), ('-lessor', 'Lessor DESC')], default='condition', max_length=20, verbose_name='order by'),
        ),
    ]
