# Generated by Django 3.0.5 on 2020-06-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200617_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['familiar_name', 'makemodel', 'inventory']},
        ),
    ]
