# Generated by Django 3.0.5 on 2020-07-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200710_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquery',
            name='makemodel_operator',
            field=models.CharField(choices=[('makemodel__iexact', 'equals')], default='makemodel__iexact', max_length=50, verbose_name='category operator'),
        ),
        migrations.AddField(
            model_name='itemquery',
            name='makemodel_use',
            field=models.BooleanField(default=False, verbose_name='use category'),
        ),
        migrations.AddField(
            model_name='itemquery',
            name='makemodel_value',
            field=models.ForeignKey(blank=True, help_text="The item's model", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_query', to='inventory.MakeModel', verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='makemodel_category_operator',
            field=models.CharField(choices=[('makemodel__category__id__iexact', 'equals')], default='makemodel__category__id__iexact', max_length=50, verbose_name='category operator'),
        ),
    ]
