# Generated by Django 3.0.5 on 2020-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200711_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquery',
            name='makemodel_category_operator',
            field=models.CharField(choices=[('makemodel__makemodelxcategory__category__exact', 'equals')], default='makemodel__makemodelxcategory__category__exact', max_length=50, verbose_name='category operator'),
        ),
        migrations.RemoveField(
            model_name='itemquery',
            name='makemodel_category_value',
        ),
        migrations.AddField(
            model_name='itemquery',
            name='makemodel_category_value',
            field=models.ManyToManyField(blank=True, help_text="The item's model's category", related_name='item_query_category', to='inventory.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='makemodel_operator',
            field=models.CharField(choices=[('makemodel__exact', 'equals')], default='makemodel__exact', max_length=50, verbose_name='model operator'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='makemodel_use',
            field=models.BooleanField(default=False, verbose_name='use model'),
        ),
        migrations.AlterField(
            model_name='itemquery',
            name='roles_operator',
            field=models.CharField(choices=[('itemxrole__role__in', 'are in'), ('exclude__itemxrole__role__in', 'are not in')], default='itemxrole__role__in', max_length=50, verbose_name='roles operator'),
        ),
    ]
