# Generated by Django 3.0.5 on 2020-06-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0002_auto_20200508_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityXRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this list', max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'list',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='contact_list',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='entity',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['sort_code', 'full_name']},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='part_of',
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.IntegerField(choices=[(1, 'Organization'), (2, 'Department'), (3, 'Division'), (10, 'Individual')], help_text='The type of entity', null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='entity',
            name='full_name',
            field=models.CharField(default='', help_text='Full name, ex: "Benjamin Goldberg", "Technology and Content Strategy"', max_length=75, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='job_title',
            field=models.CharField(blank=True, help_text="The person's job title", max_length=50, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='entity',
            name='member_of',
            field=models.ForeignKey(blank=True, help_text='The entity of which this entity is a part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='short_name',
            field=models.CharField(default='', help_text='A familiar name, short name, or abbreviation, ex:"Ben", "TCS"', max_length=10, verbose_name='Short Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='sort_code',
            field=models.CharField(default='', help_text='A string to use for sorting in a list. ex: "_", "A", "ZZZ".  Default sorting will be on type, sort code, then full name ', max_length=10, verbose_name='Sort Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="The person who is this person's supervisor", limit_choices_to={'entity_type': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='smsphone',
            name='name',
            field=models.CharField(default='', help_text='Name of phone (ex: "Work", "Home", "Mobile")', max_length=15, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity who has this email address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with this entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smsphone',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity who has this phone number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='voicephone',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity who has this phone number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Entity', verbose_name='Entity'),
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='entityxroll',
            name='entity',
            field=models.ForeignKey(help_text='The entity that is on this list', on_delete=django.db.models.deletion.CASCADE, related_name='entityxroll', to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='entityxroll',
            name='roll',
            field=models.ForeignKey(help_text='The list that includes this entity', on_delete=django.db.models.deletion.CASCADE, related_name='entityxroll', to='entities.Roll'),
        ),
    ]
