# Generated by Django 3.0.5 on 2020-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200417_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='kind',
            field=models.CharField(choices=[('GR', 'Group'), ('IN', 'Individual')], default='IN', help_text='The kind of entity', max_length=2, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
