# Generated by Django 3.0.5 on 2020-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200617_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, help_text='Name of email (ex: "Work", "Home", "Mobile")', max_length=15, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='roll',
            name='sort_code',
            field=models.CharField(blank=True, help_text='A string to use for sorting in a list. ex: "_", "A", "ZZZ".  Default sorting will be on type, sort code, then full name ', max_length=10, verbose_name='Sort Code'),
        ),
        migrations.AddField(
            model_name='voicephone',
            name='name',
            field=models.CharField(blank=True, help_text='Name of phone (ex: "Work", "Home", "Mobile")', max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sort_code',
            field=models.CharField(blank=True, help_text='A string to use for sorting in a list. ex: "_", "A", "ZZZ".  Default sorting will be on type, sort code, then full name ', max_length=10, verbose_name='Sort Code'),
        ),
        migrations.AlterField(
            model_name='smsphone',
            name='name',
            field=models.CharField(blank=True, help_text='Name of phone (ex: "Work", "Home", "Mobile")', max_length=15, verbose_name='Name'),
        ),
    ]
