# Generated by Django 3.0.5 on 2020-06-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20200617_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['entity_type', 'sort_code', 'full_name']},
        ),
        migrations.AlterModelOptions(
            name='roll',
            options={'ordering': ['sort_code', 'name']},
        ),
        migrations.AlterField(
            model_name='entity',
            name='sort_code',
            field=models.CharField(blank=True, default='|', help_text='A string to use for sorting in a list. ex: "_", "A", "zzz", "|".  Default sorting will be on type, sort code, then full name ', max_length=10, verbose_name='Sort Code'),
        ),
        migrations.AlterField(
            model_name='entityxroll',
            name='entity',
            field=models.ForeignKey(help_text='The entity that is on this roll', on_delete=django.db.models.deletion.CASCADE, related_name='entityxroll', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='entityxroll',
            name='roll',
            field=models.ForeignKey(help_text='The roll that includes this entity', on_delete=django.db.models.deletion.CASCADE, related_name='entityxroll', to='entities.Roll'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='name',
            field=models.CharField(help_text='The name of this roll', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='sort_code',
            field=models.CharField(blank=True, default='|', help_text='A string to use for sorting in a list. ex: "_", "A", "zzz", "|".  Default sorting will be on sort code, name ', max_length=10, verbose_name='Sort Code'),
        ),
    ]
